name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: Denobi # Substitua pelo seu username do GitHub
          outputs: dist/snake.svg

      - name: Commitar e enviar a animação
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Atualizar Snake Game"
          git push
